// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package gRPC_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GetEndpointClient is the client API for GetEndpoint service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetEndpointClient interface {
	Send(ctx context.Context, in *EndpointRequest, opts ...grpc.CallOption) (*EndpointResponse, error)
}

type getEndpointClient struct {
	cc grpc.ClientConnInterface
}

func NewGetEndpointClient(cc grpc.ClientConnInterface) GetEndpointClient {
	return &getEndpointClient{cc}
}

func (c *getEndpointClient) Send(ctx context.Context, in *EndpointRequest, opts ...grpc.CallOption) (*EndpointResponse, error) {
	out := new(EndpointResponse)
	err := c.cc.Invoke(ctx, "/gRPC_api.GetEndpoint/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetEndpointServer is the server API for GetEndpoint service.
// All implementations must embed UnimplementedGetEndpointServer
// for forward compatibility
type GetEndpointServer interface {
	Send(context.Context, *EndpointRequest) (*EndpointResponse, error)
	mustEmbedUnimplementedGetEndpointServer()
}

// UnimplementedGetEndpointServer must be embedded to have forward compatible implementations.
type UnimplementedGetEndpointServer struct {
}

func (UnimplementedGetEndpointServer) Send(context.Context, *EndpointRequest) (*EndpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedGetEndpointServer) mustEmbedUnimplementedGetEndpointServer() {}

// UnsafeGetEndpointServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetEndpointServer will
// result in compilation errors.
type UnsafeGetEndpointServer interface {
	mustEmbedUnimplementedGetEndpointServer()
}

func RegisterGetEndpointServer(s grpc.ServiceRegistrar, srv GetEndpointServer) {
	s.RegisterService(&GetEndpoint_ServiceDesc, srv)
}

func _GetEndpoint_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetEndpointServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gRPC_api.GetEndpoint/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetEndpointServer).Send(ctx, req.(*EndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetEndpoint_ServiceDesc is the grpc.ServiceDesc for GetEndpoint service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetEndpoint_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gRPC_api.GetEndpoint",
	HandlerType: (*GetEndpointServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _GetEndpoint_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/gRPC/endpoint.proto",
}
